version: '3.8'

services:
  web:
    build: ./backend
    # Se sobrescribe el comando por si en el futuro se quiere cambiar (ej. para usar daphne/gunicorn)
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

